base_config: configs/base.yaml
data_config: configs/tum/base.yaml

Tracking:
    orb_config: configs/tum/orb_tum1.yaml
    orb_voc: submodules/orb_slam_deps/ORB-SLAM2-PYBIND/Vocabulary/ORBvoc.txt

Dataset:
    scene: fr1_desk
    dataset_path: datasets/tum/rgbd_dataset_freiburg1_desk
    Calibration:
        fx: 517.306408
        fy: 516.469215
        cx: 318.643040
        cy: 255.313989
        k1: 0.262383
        k2: -0.953104
        p1: -0.005358
        p2: 0.002628
        k3: 1.163314
        distorted: True
        width: 640
        height: 480
        depth_scale: 5000.0
