base_config: configs/base.yaml
data_config: configs/tum/base.yaml

Tracking:
    orb_config: configs/tum/orb_tum2.yaml
    orb_voc: submodules/orb_slam_deps/ORB-SLAM2-PYBIND/Vocabulary/ORBvoc.txt

Dataset:
    scene: fr2_xyz
    dataset_path: datasets/tum/rgbd_dataset_freiburg2_xyz
    Calibration:
        fx: 520.90862
        fy: 521.007327
        cx: 325.141442
        cy: 249.701764
        k1: 0.2312
        k2: -0.7849
        p1: -0.0033
        p2: -0.0001
        k3: 0.9172
        distorted: True
        width: 640
        height: 480
        depth_scale: 5000.0
