base_config: configs/base.yaml
data_config: configs/tum/base.yaml

Tracking:
    orb_config: configs/tum/orb_tum3.yaml
    orb_voc: submodules/orb_slam_deps/ORB-SLAM2-PYBIND/Vocabulary/ORBvoc.txt

Dataset:
    scene: fr3_office
    dataset_path: datasets/tum/rgbd_dataset_freiburg3_long_office_household
    Calibration:
        fx: 535.4
        fy: 539.2
        cx: 320.1
        cy: 247.6
        k1: 0.0
        k2: 0.0
        p1: 0.0
        p2: 0.0
        k3: 0.0
        distorted: False
        width: 640
        height: 480
        depth_scale: 5000.0
