base_config: configs/base.yaml
data_config: configs/scannetpp/base.yaml

Dataset:
    scene: '8b5caf3398'
    dataset_path: "datasets/scannetpp/8b5caf3398/"
    Calibration: # camera intrinsics before distortion or undisorted
        fx: 632.767531983479
        fy: 638.3729872535719
        cx: 876.0
        cy: 584.0
        k1: 0
        k2: 0
        p1: 0
        p2: 0
        k3: 0
        width: 1752
        height: 1168
        depth_scale: 1000.0
        distorted: False