base_config: configs/base.yaml
data_config: configs/scannetpp/base.yaml

Dataset:
    scene: 'f34d532901'
    dataset_path: "datasets/scannetpp/f34d532901/"
    Calibration: # camera intrinsics before distortion or undisorted
        fx: 625.0007233945491
        fy: 625.3799394651107
        cx: 876.0
        cy: 584.0
        k1: 0
        k2: 0
        p1: 0
        p2: 0
        k3: 0
        width: 1752
        height: 1168
        depth_scale: 1000.0
        distorted: False